apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-conf

data:
  default.conf: |
    server {
      listen 80;
      location / {
        return 200 'homepage';
      }
      location = /ready {
        return 200 'I am ready';
      }
    }
