apiVersion: v1
kind: Service
metadata:
  name: ngx-svc
  labels:
    app: ngx-svc

spec:
  # type: ClusterIP
  type: NodePort
  selector:
    app: ngx-dep
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
