apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-conf
  labels:
    app: rollout-demo

data:
  default.conf: |
    server {
      listen 80;
      location / {
        default_type text/plain;
        return 200
          'ver : $nginx_version\nsrv : $server_addr:$server_port\nhost: $hostname\n';
      }
    }
