# kubectl create service clusterip ngx-svc --http=80 $out

apiVersion: v1
kind: Service
metadata:
  name: ngx-svc
  labels:
    app: rollout-demo

spec:
  selector:
    app: ngx-dep

  type: ClusterIP
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
