apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-pod
  name: busy-pod
spec:
  containers:
  - image: busybox:latest
    imagePullPolicy: IfNotPresent
    name: busy
    env:
      - name: os
        value: "ubuntu"
      - name: debug
        value: "on"
    command:
      - /bin/echo
    args:
      - "$(os), $(debug)"
